### ISSUE TITLE
Unable to compile the kernel

### ISSUE THREAD

**Issue by B83C** [adeii/huawei-london-kernel#1]
Hello, I kept getting this issue when compiling the kernel : 
```
aarch64-none-elf-ld: kernel/built-in.o: in function `free_task':
/home/arm/git/huawei-london-kernel/kernel/fork.c:229: undefined reference to `cpufreq_task_stats_exit'
/home/arm/git/huawei-london-kernel/kernel/fork.c:229:(.text+0x9a0): relocation truncated to fit: R_AARCH64_CALL26 against undefined symbol `cpufreq_task_stats_exit'
make[1]: *** [Makefile:982: vmlinux] Error 1
make: *** [Makefile:540: __build_one_by_one] Error 2
Command exited with non-zero status 2
```
It happens without regard to the compiler I used ( aarch64-none-elfgcc on alpine musl (aarch64) or eva-gcc 12 on debian) 
I have also tried looking for the definition of the function using grep in the kernel root but only its declaration could be found.

Have you any idea?

**Comment by adeii** [comment]
See one or two commits before for certain file (kernel/fork.c) https://github.com/adeii/huawei-london-kernel/commit/3053ff3e3dd232e1250e8ab35ae3d5dfe92b10d8#diff-cc1a82129952a910fdc4292448c2a097a2ba538bebefcf3c06381e45639ae73e

Solution:
remove
#ifdef CONFIG_CPU_FREQ_STAT
	cpufreq_task_stats_exit(tsk);
#endif
from kernel/fork.c
